# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-28 23:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stores',
            fields=[
                ('store_id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('url', models.CharField(max_length=400)),
                ('timezone', models.CharField(max_length=255)),
                ('img_url', models.CharField(max_length=200)),
                ('cover_img_url', models.CharField(max_length=400)),
            ],
            options={
                'db_table': 'stores',
            },
        ),
    ]
