# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-28 23:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotions',
            fields=[
                ('promotion_id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=250)),
                ('url', models.CharField(max_length=250)),
                ('active', models.BooleanField(default=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('img_url', models.CharField(max_length=250)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.Clients')),
            ],
            options={
                'db_table': 'promotions',
            },
        ),
        migrations.CreateModel(
            name='PromotionsOnStores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promotion.Promotions')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Stores')),
            ],
            options={
                'db_table': 'promotions_on_stores',
            },
        ),
        migrations.CreateModel(
            name='PromotionsStatus',
            fields=[
                ('promotions_status_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'promotions_status',
            },
        ),
        migrations.CreateModel(
            name='PromotionsType',
            fields=[
                ('promotion_type_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'promotions_type',
            },
        ),
        migrations.AddField(
            model_name='promotions',
            name='promotion_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promotion.PromotionsStatus'),
        ),
        migrations.AddField(
            model_name='promotions',
            name='promotion_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promotion.PromotionsType'),
        ),
    ]
