# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-28 23:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('brand_id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('url', models.CharField(max_length=200)),
                ('timezone', models.CharField(max_length=255)),
                ('cover_img_url', models.CharField(max_length=200)),
                ('lowercolor', models.CharField(max_length=7)),
                ('uppercolor', models.CharField(max_length=7)),
            ],
            options={
                'db_table': 'brands',
            },
        ),
    ]
