# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-29 03:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensors',
            fields=[
                ('sensor_id', models.IntegerField(primary_key=True, serialize=False)),
                ('sid', models.CharField(max_length=120)),
                ('model', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=200)),
                ('mac', models.CharField(max_length=17)),
                ('call_home', models.BooleanField()),
                ('rate', models.DecimalField(decimal_places=5, max_digits=8)),
                ('public_key', models.TextField()),
                ('essid', models.CharField(max_length=200)),
                ('register_time', models.DateTimeField()),
                ('sensor_ip', models.CharField(max_length=100)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Departments')),
            ],
            options={
                'db_table': 'sensors',
            },
        ),
    ]
