# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-29 02:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensors',
            old_name='departament',
            new_name='department',
        ),
    ]
