# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-29 02:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0002_auto_20160129_0247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensors',
            old_name='department',
            new_name='departments',
        ),
    ]
