# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-29 02:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0003_auto_20160129_0249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensors',
            old_name='departments',
            new_name='department',
        ),
    ]
