# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-03 04:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('device_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('mac', models.CharField(max_length=17)),
                ('type', models.CharField(max_length=250)),
                ('family', models.CharField(max_length=30)),
                ('os_family', models.CharField(max_length=30)),
                ('os_version', models.CharField(max_length=100)),
                ('first_seen', models.DateTimeField()),
                ('last_seen', models.DateTimeField()),
                ('user_agent', models.TextField()),
            ],
            options={
                'db_table': 'devices',
            },
        ),
        migrations.CreateModel(
            name='Vendors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oui', models.CharField(max_length=17)),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'vendor',
            },
        ),
        migrations.AddField(
            model_name='devices',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.Vendors'),
        ),
    ]
