# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-03 04:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('employee_id', models.IntegerField(primary_key=True, serialize=False)),
                ('language', models.CharField(max_length=2)),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'employees',
            },
        ),
        migrations.CreateModel(
            name='EmployeesStores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Employees')),
            ],
            options={
                'db_table': 'employees_stores',
            },
        ),
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('permission_id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'permissions',
            },
        ),
        migrations.CreateModel(
            name='PermissionsRoles',
            fields=[
                ('permission_role_id', models.IntegerField(primary_key=True, serialize=False)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Permissions')),
            ],
            options={
                'db_table': 'permissions_roles',
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('rol_id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.AddField(
            model_name='permissionsroles',
            name='rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Roles'),
        ),
        migrations.AddField(
            model_name='employeesstores',
            name='rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Roles'),
        ),
        migrations.AddField(
            model_name='employeesstores',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Stores'),
        ),
    ]
