# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-11 15:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 11, 15, 23, 16, 267239), editable=False),
        ),
        migrations.AlterField(
            model_name='departments',
            name='register_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 11, 15, 23, 16, 294895)),
        ),
        migrations.AlterField(
            model_name='stores',
            name='register_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 11, 15, 23, 16, 292314)),
        ),
    ]
