# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-13 02:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20160213_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brands',
            name='register_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 13, 2, 3, 13, 390647)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 13, 2, 3, 13, 364211), editable=False),
        ),
        migrations.AlterField(
            model_name='departments',
            name='register_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 13, 2, 3, 13, 389079)),
        ),
        migrations.AlterField(
            model_name='promotions',
            name='expiration_time_range',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 13, 2, 3, 13, 393987)),
        ),
        migrations.AlterField(
            model_name='promotions',
            name='register_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 13, 2, 3, 13, 393613)),
        ),
        migrations.AlterField(
            model_name='promotionsimpacts',
            name='impact_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 2, 13, 2, 3, 13, 395990), null=True),
        ),
        migrations.AlterField(
            model_name='sensors',
            name='register_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 13, 2, 3, 13, 389862), null=True),
        ),
        migrations.AlterField(
            model_name='stores',
            name='register_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 13, 2, 3, 13, 383551)),
        ),
    ]
