# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-11 15:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20160211_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 11, 15, 26, 49, 83885), editable=False),
        ),
        migrations.AlterField(
            model_name='departments',
            name='register_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 11, 15, 26, 49, 117556)),
        ),
        migrations.AlterField(
            model_name='stores',
            name='register_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 11, 15, 26, 49, 114618)),
        ),
    ]
