# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-11 18:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20160211_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('brand_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('brand_name', models.CharField(max_length=100)),
                ('register_date', models.DateTimeField(default=datetime.datetime(2016, 2, 11, 18, 54, 13, 326230))),
                ('telephone', models.CharField(max_length=50)),
                ('web_site', models.URLField(blank=True, null=True)),
                ('description', models.CharField(max_length=250)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('background_color', models.CharField(default='#ffffff', max_length=7)),
                ('foreground_color', models.CharField(default='#ffffff', max_length=7)),
                ('backgroud_img', models.ImageField(upload_to='media')),
                ('ttf_font', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('promotion_enable', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Clients')),
            ],
            options={
                'db_table': 'brands',
            },
        ),
        migrations.CreateModel(
            name='Promotions',
            fields=[
                ('promotion_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('promotion_name', models.CharField(max_length=100)),
                ('register_date', models.DateTimeField(default=datetime.datetime(2016, 2, 11, 18, 54, 13, 327654))),
                ('description', models.TextField()),
                ('short_description', models.CharField(max_length=100)),
                ('long_description', models.TextField()),
                ('url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('A', 'Accepted'), ('D', 'Denied')], default='P', max_length=1)),
                ('active', models.BooleanField(default=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('monday', models.BooleanField(default=True)),
                ('tuesday', models.BooleanField(default=True)),
                ('wednesday', models.BooleanField(default=True)),
                ('thursday', models.BooleanField(default=True)),
                ('friday', models.BooleanField(default=True)),
                ('saturday', models.BooleanField(default=True)),
                ('sunday', models.BooleanField(default=True)),
                ('img_url', models.URLField(blank=True, null=True)),
                ('email_send', models.BooleanField(default=True)),
                ('expiration_time_range', models.DateTimeField(default=datetime.datetime(2016, 2, 11, 18, 54, 13, 328016))),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Clients')),
            ],
            options={
                'db_table': 'promotions',
            },
        ),
        migrations.CreateModel(
            name='Promotions_types',
            fields=[
                ('promotion_type_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'promotions_types',
            },
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 11, 18, 54, 13, 309625), editable=False),
        ),
        migrations.AlterField(
            model_name='departments',
            name='register_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 11, 18, 54, 13, 325584)),
        ),
        migrations.AlterField(
            model_name='stores',
            name='register_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 11, 18, 54, 13, 324167)),
        ),
    ]
