# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-11 18:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20160211_1854'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Promotions_types',
            new_name='PromotionsTypes',
        ),
        migrations.RenameModel(
            old_name='StoreTags',
            new_name='StoresTags',
        ),
        migrations.AlterField(
            model_name='brands',
            name='register_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 11, 18, 56, 57, 297698)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 11, 18, 56, 57, 280894), editable=False),
        ),
        migrations.AlterField(
            model_name='departments',
            name='register_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 11, 18, 56, 57, 297058)),
        ),
        migrations.AlterField(
            model_name='promotions',
            name='expiration_time_range',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 11, 18, 56, 57, 299500)),
        ),
        migrations.AlterField(
            model_name='promotions',
            name='register_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 11, 18, 56, 57, 299146)),
        ),
        migrations.AlterField(
            model_name='stores',
            name='register_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 11, 18, 56, 57, 295603)),
        ),
        migrations.AlterModelTable(
            name='storestags',
            table='stores_tags',
        ),
    ]
