# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-11 20:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20160211_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionsFilters',
            fields=[
                ('promotion_filter', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('promotion_filter_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'promotions_filters',
            },
        ),
        migrations.CreateModel(
            name='PromotionsImpacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impact_time', models.DateTimeField(blank=True, default=datetime.datetime(2016, 2, 11, 20, 36, 4, 756246), null=True)),
                ('promo_code', models.CharField(blank=True, max_length=200, null=True)),
                ('check_in', models.BooleanField(default=False)),
                ('check_in_number', models.DecimalField(decimal_places=0, default=0, max_digits=3)),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'promotions_impacts',
            },
        ),
        migrations.CreateModel(
            name='PromotionsLoyalties',
            fields=[
                ('promotion', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('promotion_loyalty_name', models.CharField(max_length=50)),
                ('check_in_number', models.DecimalField(decimal_places=0, default=0, max_digits=3)),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'promotions_loyalties',
            },
        ),
        migrations.CreateModel(
            name='PromotionsSpecials',
            fields=[
                ('promotion_special', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('promotion_special_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'promotions_specials',
            },
        ),
        migrations.CreateModel(
            name='Sensors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=120, unique=True)),
                ('model', models.CharField(choices=[('Model 01', 'MR-01'), ('Model 02', 'MR-02'), ('Model 03', 'MR-03'), ('Model 04', 'MR-04'), ('Model 05', 'MR-05')], max_length=30, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('mac', models.CharField(max_length=17, unique=True)),
                ('call_home', models.BooleanField(default=False)),
                ('rate', models.FloatField(null=True)),
                ('public_key', models.CharField(max_length=700)),
                ('essid', models.CharField(max_length=200, null=True)),
                ('register_time', models.DateTimeField(default=datetime.datetime(2016, 2, 11, 20, 36, 4, 752790), null=True)),
                ('sensor_ip', models.GenericIPAddressField(null=True, protocol='IPv4')),
            ],
            options={
                'db_table': 'sensors',
            },
        ),
        migrations.CreateModel(
            name='StoresCategories',
            fields=[
                ('store_categories', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('store_categories_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'stores_categories',
            },
        ),
        migrations.RenameField(
            model_name='brands',
            old_name='brand_id',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='clients',
            old_name='client_id',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='departments',
            old_name='department_id',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='departments',
            old_name='store_id',
            new_name='store',
        ),
        migrations.RenameField(
            model_name='promotions',
            old_name='promotion_id',
            new_name='promotion',
        ),
        migrations.RenameField(
            model_name='promotionstypes',
            old_name='promotion_type_id',
            new_name='promotion_type',
        ),
        migrations.RenameField(
            model_name='stores',
            old_name='store_id',
            new_name='store',
        ),
        migrations.RenameField(
            model_name='storestags',
            old_name='store_tag_id',
            new_name='store_tag',
        ),
        migrations.RemoveField(
            model_name='cities',
            name='city_id',
        ),
        migrations.RemoveField(
            model_name='countries',
            name='country_id',
        ),
        migrations.RemoveField(
            model_name='regions',
            name='region_id',
        ),
        migrations.RemoveField(
            model_name='storestags',
            name='store_id',
        ),
        migrations.AddField(
            model_name='cities',
            name='city_name',
            field=models.CharField(default='default', max_length=100),
        ),
        migrations.AddField(
            model_name='countries',
            name='country_name',
            field=models.CharField(default='default', max_length=200),
        ),
        migrations.AddField(
            model_name='promotions',
            name='promotion_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='services.PromotionsTypes'),
        ),
        migrations.AddField(
            model_name='promotionstypes',
            name='promotion_type_name',
            field=models.CharField(default='default', max_length=50),
        ),
        migrations.AddField(
            model_name='regions',
            name='region_name',
            field=models.CharField(default='default', max_length=100),
        ),
        migrations.AddField(
            model_name='storestags',
            name='store',
            field=models.ManyToManyField(to='services.Stores'),
        ),
        migrations.AlterField(
            model_name='brands',
            name='register_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 11, 20, 36, 4, 753546)),
        ),
        migrations.AlterField(
            model_name='cities',
            name='city',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='countries',
            name='country',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 11, 20, 36, 4, 734605), editable=False),
        ),
        migrations.AlterField(
            model_name='departments',
            name='register_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 11, 20, 36, 4, 752062)),
        ),
        migrations.AlterField(
            model_name='promotions',
            name='expiration_time_range',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 11, 20, 36, 4, 757496)),
        ),
        migrations.AlterField(
            model_name='promotions',
            name='register_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 11, 20, 36, 4, 757040)),
        ),
        migrations.AlterField(
            model_name='regions',
            name='region',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stores',
            name='register_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 11, 20, 36, 4, 748414)),
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='customs_users',
        ),
        migrations.AddField(
            model_name='storescategories',
            name='store',
            field=models.ManyToManyField(to='services.Stores'),
        ),
        migrations.AddField(
            model_name='sensors',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='services.Departments'),
        ),
        migrations.AddField(
            model_name='promotionsimpacts',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Clients'),
        ),
        migrations.AddField(
            model_name='promotionsimpacts',
            name='promotion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Promotions'),
        ),
        migrations.AddField(
            model_name='promotionsimpacts',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Stores'),
        ),
        migrations.AddField(
            model_name='promotions',
            name='promotion_filter',
            field=models.ManyToManyField(to='services.PromotionsFilters'),
        ),
    ]
