# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-11 20:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_auto_20160211_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brands',
            name='register_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 11, 20, 37, 15, 709347)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 11, 20, 37, 15, 690150), editable=False),
        ),
        migrations.AlterField(
            model_name='departments',
            name='register_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 11, 20, 37, 15, 707862)),
        ),
        migrations.AlterField(
            model_name='promotions',
            name='expiration_time_range',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 11, 20, 37, 15, 713371)),
        ),
        migrations.AlterField(
            model_name='promotions',
            name='register_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 11, 20, 37, 15, 712906)),
        ),
        migrations.AlterField(
            model_name='promotionsimpacts',
            name='impact_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 2, 11, 20, 37, 15, 712082), null=True),
        ),
        migrations.AlterField(
            model_name='sensors',
            name='register_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 11, 20, 37, 15, 708592), null=True),
        ),
        migrations.AlterField(
            model_name='stores',
            name='register_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 11, 20, 37, 15, 704197)),
        ),
    ]
