# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-28 23:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('client_id', models.UUIDField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'clients',
            },
        ),
    ]
