# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-03 04:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('promotion', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupons',
            fields=[
                ('coupon_id', models.UUIDField(primary_key=True, serialize=False)),
                ('claim_time', models.DateTimeField(auto_now_add=True)),
                ('short_description', models.CharField(max_length=500)),
                ('log_description', models.TextField()),
                ('legal_statement', models.TextField()),
                ('redemption_start', models.DateTimeField()),
                ('redemption_end', models.DateTimeField()),
                ('publication_start', models.DateTimeField()),
                ('publication_end', models.DateTimeField()),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
            ],
            options={
                'db_table': 'coupons',
            },
        ),
        migrations.CreateModel(
            name='CouponsStatus',
            fields=[
                ('coupon_status_id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'coupons_status',
            },
        ),
        migrations.CreateModel(
            name='CouponsType',
            fields=[
                ('coupon_type_id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'coupons_type',
            },
        ),
        migrations.CreateModel(
            name='CouponsUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coupon.Coupons')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Users')),
            ],
            options={
                'db_table': 'coupons_users',
            },
        ),
        migrations.AddField(
            model_name='coupons',
            name='coupon_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coupon.CouponsStatus'),
        ),
        migrations.AddField(
            model_name='coupons',
            name='coupon_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coupon.CouponsType'),
        ),
        migrations.AddField(
            model_name='coupons',
            name='promotion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promotion.Promotions'),
        ),
    ]
