# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-03 04:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('client_id', models.UUIDField(primary_key=True, serialize=False)),
                ('business_name', models.CharField(max_length=250)),
                ('short_name', models.CharField(max_length=250)),
                ('prefix', models.CharField(max_length=4)),
                ('description', models.CharField(max_length=250)),
                ('telephone', models.CharField(max_length=20)),
                ('fax', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'clients',
            },
        ),
    ]
